
package CRUD;


import Conexion.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


public class Veterinaria extends javax.swing.JFrame {

    conexion con = new conexion();
    Connection conect;
    DefaultTableModel model;
    Statement st;
    ResultSet rs;
    int idc;
    public Veterinaria() {
        initComponents();
        this.setLocationRelativeTo(null);
        Consultar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtarticulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Alajuela = new javax.swing.JRadioButton();
        Heredia = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        BTNagregar = new javax.swing.JButton();
        BTNmodificar = new javax.swing.JButton();
        BTNeliminar = new javax.swing.JButton();
        BTNlimpiar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        BTNsalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Veterinaria", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 24))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setToolTipText("");

        jLabel1.setText("Nombre del Articulo");

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medicina", "Accesorio", "Comida", " " }));

        jLabel2.setText("Tipo de Articulo");

        jLabel3.setText("Precio");

        jLabel4.setText("Cantidad en el inventario");

        jLabel5.setText("Sitio donde se encuentra el articulo ");

        buttonGroup1.add(Alajuela);
        Alajuela.setText("Alajuela");
        Alajuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlajuelaActionPerformed(evt);
            }
        });

        buttonGroup1.add(Heredia);
        Heredia.setText("Heredia");

        jLabel6.setText("Fecha");

        date.setDateFormatString("yyyy/MM/dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(txtarticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Alajuela, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(Heredia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtarticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alajuela)
                    .addComponent(Heredia))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));

        BTNagregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNagregar.setText("Agregar");
        BTNagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNagregarActionPerformed(evt);
            }
        });

        BTNmodificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNmodificar.setText("Modificar");
        BTNmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNmodificarActionPerformed(evt);
            }
        });

        BTNeliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNeliminar.setText("Eliminar");
        BTNeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNeliminarActionPerformed(evt);
            }
        });

        BTNlimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNlimpiar.setText("Limpiar");
        BTNlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNlimpiarActionPerformed(evt);
            }
        });

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        BTNsalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNsalir.setText("Salir");
        BTNsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(BTNagregar)
                .addGap(58, 58, 58)
                .addComponent(BTNmodificar)
                .addGap(35, 35, 35)
                .addComponent(BTNeliminar)
                .addGap(18, 18, 18)
                .addComponent(BTNlimpiar)
                .addGap(155, 155, 155)
                .addComponent(btnReporte)
                .addGap(309, 309, 309))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(721, 721, 721)
                    .addComponent(BTNsalir)
                    .addContainerGap(432, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReporte)
                    .addComponent(BTNmodificar)
                    .addComponent(BTNagregar)
                    .addComponent(BTNeliminar)
                    .addComponent(BTNlimpiar))
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(BTNsalir)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        Table.setBorder(javax.swing.BorderFactory.createTitledBorder("table"));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Articulo", "fecha", "precio", "cantidad", "sitio", "tipo"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlajuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlajuelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlajuelaActionPerformed

    private void BTNagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNagregarActionPerformed

        // TODO add your handling code here:
        Agregar();
        Consultar();
    }//GEN-LAST:event_BTNagregarActionPerformed

    private void BTNmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNmodificarActionPerformed
        // TODO add your handling code here:

        modificarRegistro();
    }//GEN-LAST:event_BTNmodificarActionPerformed

    private void BTNeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNeliminarActionPerformed
        // TODO add your handling code here:
        eliminarRegistro();
    }//GEN-LAST:event_BTNeliminarActionPerformed

    private void BTNlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNlimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_BTNlimpiarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnReporteActionPerformed

    private void BTNsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsalirActionPerformed
        // TODO add your handling code here:

        int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que quieres salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0); // Cierra la aplicación
        }

    }//GEN-LAST:event_BTNsalirActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
      
    int fila = Table.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "Seleccione una fila ");
    } else {
        // Obtener los valores actuales de la tabla
        int idc = Integer.parseInt(Table.getValueAt(fila, 0).toString());
        String articulo = Table.getValueAt(fila, 1).toString(); // ARTICULO
        String fecha = Table.getValueAt(fila, 2).toString();    // FECHA
        String precio = Table.getValueAt(fila, 3).toString();    // PRECIO
        String cantidad = Table.getValueAt(fila, 4).toString();  // CANTIDAD
        String sitio = Table.getValueAt(fila, 5).toString();     // SITIO
        String tipo = Table.getValueAt(fila, 6).toString();      // TIPO

        // Convertir el texto de la fecha a un objeto java.util.Date
        java.util.Date fecha2 = null;
        try {
            if (fecha != null && !fecha.trim().isEmpty()) {
                fecha2 = new SimpleDateFormat("yyyy-MM-dd").parse(fecha);
                date.setDate(fecha2);
            } else {
                JOptionPane.showMessageDialog(null, "Fecha no válida o vacía.");
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Error en el formato de la fecha: " + e.getMessage());
        }

        // Asignar los valores a los campos de texto y otros componentes
        txtarticulo.setText(articulo);
        txtprecio.setText(precio);
        txtcantidad.setText(cantidad);

        if (sitio.equals("Alajuela")) {
            Alajuela.setSelected(true);
            Heredia.setSelected(false);
        } else if (sitio.equals("Heredia")) {
            Alajuela.setSelected(false);
            Heredia.setSelected(true);
        }

        cboTipo.setSelectedItem(tipo);
    }
    }//GEN-LAST:event_TableMouseClicked
    void Consultar() {
    String sql = "SELECT * FROM notas";
    try {
        if (conect == null || conect.isClosed()) {
            conect = con.getConnection(); // Vuelve a conectar si la conexión está cerrada
        }
        
        st = conect.createStatement();
        rs = st.executeQuery(sql);
        
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0); // Limpiar todas las filas existentes
        
        while (rs.next()) {
            Object[] dato = new Object[7];
            dato[0] = rs.getInt("id");
            dato[1] = rs.getDate("articulo");
            dato[2] = rs.getString("fecha");
            dato[3] = rs.getString("precio");
            dato[4] = rs.getString("cantidad");
            dato[5] = rs.getString("sitio");
            dato[6] = rs.getDouble("tipo");
            model.addRow(dato);
        }
        
        Table.setModel(model);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al consultar datos: " + e.getMessage());
    } finally {
        // Cerrar recursos en el bloque finally
        try {
            if (rs != null) rs.close();
            if (st != null) st.close();
            // No cerrar 'conect' aquí, puede necesitar ser reutilizado
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cerrar conexión: " + ex.getMessage());
        }
    }
}

    
void modificarRegistro() {
    int filaSeleccionada = Table.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para modificar.");
        return;
    }

    // Obtener los valores actuales de la tabla
    String id = Table.getValueAt(filaSeleccionada, 0).toString();
    String fecha = Table.getValueAt(filaSeleccionada, 2).toString(); // FECHA
    String articulo = Table.getValueAt(filaSeleccionada, 1).toString(); // ARTICULO
    String precio = Table.getValueAt(filaSeleccionada, 3).toString(); // PRECIO
    String cantidad = Table.getValueAt(filaSeleccionada, 4).toString(); // CANTIDAD
    String sitio = Table.getValueAt(filaSeleccionada, 5).toString(); // SITIO
    String tipo = Table.getValueAt(filaSeleccionada, 6).toString(); // TIPO

    // Obtener los nuevos valores desde los campos de texto u otros componentes
    String nuevoArticulo = txtarticulo.getText();
    String nuevoPrecio = txtprecio.getText();
    String nuevoTipo = cboTipo.getSelectedItem().toString();
    String nuevoSitio = Alajuela.isSelected() ? "Alajuela" : "Heredia";
    String nuevaCantidad = txtcantidad.getText();

    try {
        if (nuevoArticulo.isEmpty() || nuevoPrecio.isEmpty() || nuevoTipo.isEmpty() || nuevoSitio.isEmpty() || nuevaCantidad.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Revise los datos");
        } else {
            // Verificar si los nuevos datos son diferentes a los actuales
            if (nuevoArticulo.equals(articulo) && nuevoPrecio.equals(precio) && nuevoTipo.equals(tipo) && nuevoSitio.equals(sitio) && nuevaCantidad.equals(cantidad)) {
                JOptionPane.showMessageDialog(null, "No se realizaron cambios.");
                return;
            }

            String sql = "UPDATE veterinaria SET fecha='" + fecha + "', articulo='" + nuevoArticulo + "', precio=" + nuevoPrecio + ", cantidad=" + nuevaCantidad + ", sitio='" + nuevoSitio + "', tipo='" + nuevoTipo + "' WHERE id=" + id;
            conect = con.getConnection();
            st = conect.createStatement();
            int resultado = st.executeUpdate(sql);

            if (resultado > 0) {
                JOptionPane.showMessageDialog(null, "Registro actualizado con éxito");

                // Limpiar campos de texto
                limpiarCampos();

                // Actualizar y limpiar tabla
                Consultar(); // Asegúrate de que este método actualice correctamente la tabla
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el registro para actualizar");
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al actualizar el registro: " + e.getMessage());
    }
}


void limpiarCampos() {
    
    txtarticulo.setText("");  // Limpia el campo de nombre
    txtprecio.setText("");  
    txtcantidad.setText("");
  
    
}

    
void Agregar() {
        String sitio = "";
        if (Alajuela.isSelected()) {
            sitio = Alajuela.getText();
        } else if (Heredia.isSelected()) {
            sitio = Heredia.getText();
        }

        String articulo = txtarticulo.getText();
        String tipo = cboTipo.getSelectedItem().toString();
        String fecha = ((JTextField) date.getDateEditor().getUiComponent()).getText();
        Double precio = Double.parseDouble(txtprecio.getText());
        Double cantidad = Double.parseDouble(txtcantidad.getText());
        DecimalFormat df = new DecimalFormat("###.##");

        // Aquí puedes continuar con lo que necesites hacer con los datos
        System.out.println("Sitio: " + sitio);
        System.out.println("Artículo: " + articulo);
        System.out.println("Tipo: " + tipo);
        System.out.println("Fecha: " + fecha);
        System.out.println("Precio: " + df.format(precio));
        System.out.println("Cantidad: " + df.format(cantidad));
    }

    void eliminarRegistro() {
    int filaSeleccionada = Table.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar.");
        return;
    }
    
    int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este registro?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
    if (confirmacion != JOptionPane.YES_OPTION) {
        return;
    }
    
    String id = Table.getValueAt(filaSeleccionada, 0).toString();
    
    try {
        String sql = "DELETE FROM veterinaria WHERE id=" + id;
        conect = con.getConnection();
        st = conect.createStatement();
        int resultado = st.executeUpdate(sql);
        
        if (resultado > 0) {
            JOptionPane.showMessageDialog(null, "Registro eliminado con éxito");
            // Eliminar la fila de la tabla en la interfaz gráfica
            DefaultTableModel model = (DefaultTableModel) Table.getModel();
            model.removeRow(filaSeleccionada);
            Table.setModel(model); // Actualizar la tabla
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el registro para eliminar");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al eliminar el registro: " + e.getMessage());
    } finally {
        // Cerrar recursos en el bloque finally
        try {
            if (st != null) st.close();
            if (conect != null) conect.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cerrar conexión: " + ex.getMessage());
        }
    }
}

     
void LimpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) Table.getModel();
        int rowCount = modelo.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }



  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Veterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Veterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Veterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Veterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Veterinaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Alajuela;
    private javax.swing.JButton BTNagregar;
    private javax.swing.JButton BTNeliminar;
    private javax.swing.JButton BTNlimpiar;
    private javax.swing.JButton BTNmodificar;
    private javax.swing.JButton BTNsalir;
    private javax.swing.JRadioButton Heredia;
    private javax.swing.JTable Table;
    private javax.swing.JButton btnReporte;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cboTipo;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtarticulo;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
